jQuery.ui||function(b){var a=b.fn.remove,c=b.browser.mozilla&&parseFloat(b.browser.version)<1.9;b.ui={version:"1.7.2",plugin:{add:function(e,f,h){e=b.ui[e].prototype;for(var k in h){e.plugins[k]=e.plugins[k]||[];e.plugins[k].push([f,h[k]])}},call:function(e,f,h){if((f=e.plugins[f])&&e.element[0].parentNode)for(var k=0;k<f.length;k++)e.options[f[k][0]]&&f[k][1].apply(e.element,h)}},contains:function(e,f){return document.compareDocumentPosition?e.compareDocumentPosition(f)&16:e!==f&&e.contains(f)},
hasScroll:function(e,f){if(b(e).css("overflow")=="hidden")return false;f=f&&f=="left"?"scrollLeft":"scrollTop";var h=false;if(e[f]>0)return true;e[f]=1;h=e[f]>0;e[f]=0;return h},isOverAxis:function(e,f,h){return e>f&&e<f+h},isOver:function(e,f,h,k,l,m){return b.ui.isOverAxis(e,h,l)&&b.ui.isOverAxis(f,k,m)},keyCode:{BACKSPACE:8,CAPS_LOCK:20,COMMA:188,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,
NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38}};if(c){var d=b.attr,j=b.fn.removeAttr,g="http://www.w3.org/2005/07/aaa",i=/^aria-/,o=/^wairole:/;b.attr=function(e,f,h){var k=h!==undefined;return f=="role"?k?d.call(this,e,f,"wairole:"+h):(d.apply(this,arguments)||"").replace(o,""):i.test(f)?k?e.setAttributeNS(g,f.replace(i,"aaa:"),h):d.call(this,e,f.replace(i,"aaa:")):d.apply(this,arguments)};b.fn.removeAttr=function(e){return i.test(e)?
this.each(function(){this.removeAttributeNS(g,e.replace(i,""))}):j.call(this,e)}}b.fn.extend({remove:function(){b("*",this).add(this).each(function(){b(this).triggerHandler("remove")});return a.apply(this,arguments)},enableSelection:function(){return this.attr("unselectable","off").css("MozUserSelect","").unbind("selectstart.ui")},disableSelection:function(){return this.attr("unselectable","on").css("MozUserSelect","none").bind("selectstart.ui",function(){return false})},scrollParent:function(){var e;
e=b.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(b.curCSS(this,"position",1))&&/(auto|scroll)/.test(b.curCSS(this,"overflow",1)+b.curCSS(this,"overflow-y",1)+b.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(b.curCSS(this,"overflow",1)+b.curCSS(this,"overflow-y",1)+b.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||
!e.length?b(document):e}});b.extend(b.expr[":"],{data:function(e,f,h){return!!b.data(e,h[3])},focusable:function(e){var f=e.nodeName.toLowerCase(),h=b.attr(e,"tabindex");return(/input|select|textarea|button|object/.test(f)?!e.disabled:"a"==f||"area"==f?e.href||!isNaN(h):!isNaN(h))&&!b(e)["area"==f?"parents":"closest"](":hidden").length},tabbable:function(e){var f=b.attr(e,"tabindex");return(isNaN(f)||f>=0)&&b(e).is(":focusable")}});function p(e,f,h,k){function l(n){n=b[e][f][n]||[];return typeof n==
"string"?n.split(/,?\s+/):n}var m=l("getter");if(k.length==1&&typeof k[0]=="string")m=m.concat(l("getterSetter"));return b.inArray(h,m)!=-1}b.widget=function(e,f){var h=e.split(".")[0];e=e.split(".")[1];b.fn[e]=function(k){var l=typeof k=="string",m=Array.prototype.slice.call(arguments,1);if(l&&k.substring(0,1)=="_")return this;if(l&&p(h,e,k,m)){var n=b.data(this[0],e);return n?n[k].apply(n,m):undefined}return this.each(function(){var q=b.data(this,e);!q&&!l&&b.data(this,e,new b[h][e](this,k))._init();
q&&l&&b.isFunction(q[k])&&q[k].apply(q,m)})};b[h]=b[h]||{};b[h][e]=function(k,l){var m=this;this.namespace=h;this.widgetName=e;this.widgetEventPrefix=b[h][e].eventPrefix||e;this.widgetBaseClass=h+"-"+e;this.options=b.extend({},b.widget.defaults,b[h][e].defaults,b.metadata&&b.metadata.get(k)[e],l);this.element=b(k).bind("setData."+e,function(n,q,r){if(n.target==k)return m._setData(q,r)}).bind("getData."+e,function(n,q){if(n.target==k)return m._getData(q)}).bind("remove",function(){return m.destroy()})};
b[h][e].prototype=b.extend({},b.widget.prototype,f);b[h][e].getterSetter="option"};b.widget.prototype={_init:function(){},destroy:function(){this.element.removeData(this.widgetName).removeClass(this.widgetBaseClass+"-disabled "+this.namespace+"-state-disabled").removeAttr("aria-disabled")},option:function(e,f){var h=e,k=this;if(typeof e=="string"){if(f===undefined)return this._getData(e);h={};h[e]=f}b.each(h,function(l,m){k._setData(l,m)})},_getData:function(e){return this.options[e]},_setData:function(e,
f){this.options[e]=f;if(e=="disabled")this.element[f?"addClass":"removeClass"](this.widgetBaseClass+"-disabled "+this.namespace+"-state-disabled").attr("aria-disabled",f)},enable:function(){this._setData("disabled",false)},disable:function(){this._setData("disabled",true)},_trigger:function(e,f,h){var k=this.options[e];e=e==this.widgetEventPrefix?e:this.widgetEventPrefix+e;f=b.Event(f);f.type=e;if(f.originalEvent){e=b.event.props.length;for(var l;e;){l=b.event.props[--e];f[l]=f.originalEvent[l]}}this.element.trigger(f,
h);return!(b.isFunction(k)&&k.call(this.element[0],f,h)===false||f.isDefaultPrevented())}};b.widget.defaults={disabled:false};b.ui.mouse={_mouseInit:function(){var e=this;this.element.bind("mousedown."+this.widgetName,function(f){return e._mouseDown(f)}).bind("click."+this.widgetName,function(f){if(e._preventClickEvent){e._preventClickEvent=false;f.stopImmediatePropagation();return false}});if(b.browser.msie){this._mouseUnselectable=this.element.attr("unselectable");this.element.attr("unselectable",
"on")}this.started=false},_mouseDestroy:function(){this.element.unbind("."+this.widgetName);b.browser.msie&&this.element.attr("unselectable",this._mouseUnselectable)},_mouseDown:function(e){e.originalEvent=e.originalEvent||{};if(!e.originalEvent.mouseHandled){this._mouseStarted&&this._mouseUp(e);this._mouseDownEvent=e;var f=this,h=e.which==1,k=typeof this.options.cancel=="string"?b(e.target).parents().add(e.target).filter(this.options.cancel).length:false;if(!h||k||!this._mouseCapture(e))return true;
this.mouseDelayMet=!this.options.delay;if(!this.mouseDelayMet)this._mouseDelayTimer=setTimeout(function(){f.mouseDelayMet=true},this.options.delay);if(this._mouseDistanceMet(e)&&this._mouseDelayMet(e)){this._mouseStarted=this._mouseStart(e)!==false;if(!this._mouseStarted){e.preventDefault();return true}}this._mouseMoveDelegate=function(l){return f._mouseMove(l)};this._mouseUpDelegate=function(l){return f._mouseUp(l)};b(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+
this.widgetName,this._mouseUpDelegate);b.browser.safari||e.preventDefault();return e.originalEvent.mouseHandled=true}},_mouseMove:function(e){if(b.browser.msie&&!e.button)return this._mouseUp(e);if(this._mouseStarted){this._mouseDrag(e);return e.preventDefault()}if(this._mouseDistanceMet(e)&&this._mouseDelayMet(e))(this._mouseStarted=this._mouseStart(this._mouseDownEvent,e)!==false)?this._mouseDrag(e):this._mouseUp(e);return!this._mouseStarted},_mouseUp:function(e){b(document).unbind("mousemove."+
this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);if(this._mouseStarted){this._mouseStarted=false;this._preventClickEvent=e.target==this._mouseDownEvent.target;this._mouseStop(e)}return false},_mouseDistanceMet:function(e){return Math.max(Math.abs(this._mouseDownEvent.pageX-e.pageX),Math.abs(this._mouseDownEvent.pageY-e.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},
_mouseStop:function(){},_mouseCapture:function(){return true}};b.ui.mouse.defaults={cancel:null,distance:1,delay:0}}(jQuery);
(function(b){b.widget("ui.draggable",b.extend({},b.ui.mouse,{_init:function(){if(this.options.helper=="original"&&!/^(?:r|a|f)/.test(this.element.css("position")))this.element[0].style.position="relative";this.options.addClasses&&this.element.addClass("ui-draggable");this.options.disabled&&this.element.addClass("ui-draggable-disabled");this._mouseInit()},destroy:function(){if(this.element.data("draggable")){this.element.removeData("draggable").unbind(".draggable").removeClass("ui-draggable ui-draggable-dragging ui-draggable-disabled");this._mouseDestroy()}},
_mouseCapture:function(a){var c=this.options;if(this.helper||c.disabled||b(a.target).is(".ui-resizable-handle"))return false;this.handle=this._getHandle(a);if(!this.handle)return false;return true},_mouseStart:function(a){var c=this.options;this.helper=this._createHelper(a);this._cacheHelperProportions();if(b.ui.ddmanager)b.ui.ddmanager.current=this;this._cacheMargins();this.cssPosition=this.helper.css("position");this.scrollParent=this.helper.scrollParent();this.offset=this.element.offset();this.offset=
{top:this.offset.top-this.margins.top,left:this.offset.left-this.margins.left};b.extend(this.offset,{click:{left:a.pageX-this.offset.left,top:a.pageY-this.offset.top},parent:this._getParentOffset(),relative:this._getRelativeOffset()});this.originalPosition=this._generatePosition(a);this.originalPageX=a.pageX;this.originalPageY=a.pageY;c.cursorAt&&this._adjustOffsetFromHelper(c.cursorAt);c.containment&&this._setContainment();this._trigger("start",a);this._cacheHelperProportions();b.ui.ddmanager&&!c.dropBehaviour&&
b.ui.ddmanager.prepareOffsets(this,a);this.helper.addClass("ui-draggable-dragging");this._mouseDrag(a,true);return true},_mouseDrag:function(a,c){this.position=this._generatePosition(a);this.positionAbs=this._convertPositionTo("absolute");if(!c){c=this._uiHash();this._trigger("drag",a,c);this.position=c.position}if(!this.options.axis||this.options.axis!="y")this.helper[0].style.left=this.position.left+"px";if(!this.options.axis||this.options.axis!="x")this.helper[0].style.top=this.position.top+"px";
b.ui.ddmanager&&b.ui.ddmanager.drag(this,a);return false},_mouseStop:function(a){var c=false;if(b.ui.ddmanager&&!this.options.dropBehaviour)c=b.ui.ddmanager.drop(this,a);if(this.dropped){c=this.dropped;this.dropped=false}if(this.options.revert=="invalid"&&!c||this.options.revert=="valid"&&c||this.options.revert===true||b.isFunction(this.options.revert)&&this.options.revert.call(this.element,c)){var d=this;b(this.helper).animate(this.originalPosition,parseInt(this.options.revertDuration,10),function(){d._trigger("stop",
a);d._clear()})}else{this._trigger("stop",a);this._clear()}return false},_getHandle:function(a){var c=!this.options.handle||!b(this.options.handle,this.element).length?true:false;b(this.options.handle,this.element).find("*").andSelf().each(function(){if(this==a.target)c=true});return c},_createHelper:function(a){var c=this.options;a=b.isFunction(c.helper)?b(c.helper.apply(this.element[0],[a])):c.helper=="clone"?this.element.clone():this.element;a.parents("body").length||a.appendTo(c.appendTo=="parent"?
this.element[0].parentNode:c.appendTo);a[0]!=this.element[0]&&!/(fixed|absolute)/.test(a.css("position"))&&a.css("position","absolute");return a},_adjustOffsetFromHelper:function(a){if(a.left!=undefined)this.offset.click.left=a.left+this.margins.left;if(a.right!=undefined)this.offset.click.left=this.helperProportions.width-a.right+this.margins.left;if(a.top!=undefined)this.offset.click.top=a.top+this.margins.top;if(a.bottom!=undefined)this.offset.click.top=this.helperProportions.height-a.bottom+this.margins.top},
_getParentOffset:function(){this.offsetParent=this.helper.offsetParent();var a=this.offsetParent.offset();if(this.cssPosition=="absolute"&&this.scrollParent[0]!=document&&b.ui.contains(this.scrollParent[0],this.offsetParent[0])){a.left+=this.scrollParent.scrollLeft();a.top+=this.scrollParent.scrollTop()}if(this.offsetParent[0]==document.body||this.offsetParent[0].tagName&&this.offsetParent[0].tagName.toLowerCase()=="html"&&b.browser.msie)a={top:0,left:0};return{top:a.top+(parseInt(this.offsetParent.css("borderTopWidth"),
10)||0),left:a.left+(parseInt(this.offsetParent.css("borderLeftWidth"),10)||0)}},_getRelativeOffset:function(){if(this.cssPosition=="relative"){var a=this.element.position();return{top:a.top-(parseInt(this.helper.css("top"),10)||0)+this.scrollParent.scrollTop(),left:a.left-(parseInt(this.helper.css("left"),10)||0)+this.scrollParent.scrollLeft()}}else return{top:0,left:0}},_cacheMargins:function(){this.margins={left:parseInt(this.element.css("marginLeft"),10)||0,top:parseInt(this.element.css("marginTop"),
10)||0}},_cacheHelperProportions:function(){this.helperProportions={width:this.helper.outerWidth(),height:this.helper.outerHeight()}},_setContainment:function(){var a=this.options;if(a.containment=="parent")a.containment=this.helper[0].parentNode;if(a.containment=="document"||a.containment=="window")this.containment=[0-this.offset.relative.left-this.offset.parent.left,0-this.offset.relative.top-this.offset.parent.top,b(a.containment=="document"?document:window).width()-this.helperProportions.width-
this.margins.left,(b(a.containment=="document"?document:window).height()||document.body.parentNode.scrollHeight)-this.helperProportions.height-this.margins.top];if(!/^(document|window|parent)$/.test(a.containment)&&a.containment.constructor!=Array){var c=b(a.containment)[0];if(c){a=b(a.containment).offset();var d=b(c).css("overflow")!="hidden";this.containment=[a.left+(parseInt(b(c).css("borderLeftWidth"),10)||0)+(parseInt(b(c).css("paddingLeft"),10)||0)-this.margins.left,a.top+(parseInt(b(c).css("borderTopWidth"),
10)||0)+(parseInt(b(c).css("paddingTop"),10)||0)-this.margins.top,a.left+(d?Math.max(c.scrollWidth,c.offsetWidth):c.offsetWidth)-(parseInt(b(c).css("borderLeftWidth"),10)||0)-(parseInt(b(c).css("paddingRight"),10)||0)-this.helperProportions.width-this.margins.left,a.top+(d?Math.max(c.scrollHeight,c.offsetHeight):c.offsetHeight)-(parseInt(b(c).css("borderTopWidth"),10)||0)-(parseInt(b(c).css("paddingBottom"),10)||0)-this.helperProportions.height-this.margins.top]}}else if(a.containment.constructor==
Array)this.containment=a.containment},_convertPositionTo:function(a,c){if(!c)c=this.position;a=a=="absolute"?1:-1;var d=this.cssPosition=="absolute"&&!(this.scrollParent[0]!=document&&b.ui.contains(this.scrollParent[0],this.offsetParent[0]))?this.offsetParent:this.scrollParent,j=/(html|body)/i.test(d[0].tagName);return{top:c.top+this.offset.relative.top*a+this.offset.parent.top*a-(b.browser.safari&&this.cssPosition=="fixed"?0:(this.cssPosition=="fixed"?-this.scrollParent.scrollTop():j?0:d.scrollTop())*
a),left:c.left+this.offset.relative.left*a+this.offset.parent.left*a-(b.browser.safari&&this.cssPosition=="fixed"?0:(this.cssPosition=="fixed"?-this.scrollParent.scrollLeft():j?0:d.scrollLeft())*a)}},_generatePosition:function(a){var c=this.options,d=this.cssPosition=="absolute"&&!(this.scrollParent[0]!=document&&b.ui.contains(this.scrollParent[0],this.offsetParent[0]))?this.offsetParent:this.scrollParent,j=/(html|body)/i.test(d[0].tagName);if(this.cssPosition=="relative"&&!(this.scrollParent[0]!=
document&&this.scrollParent[0]!=this.offsetParent[0]))this.offset.relative=this._getRelativeOffset();var g=a.pageX,i=a.pageY;if(this.originalPosition){if(this.containment){if(a.pageX-this.offset.click.left<this.containment[0])g=this.containment[0]+this.offset.click.left;if(a.pageY-this.offset.click.top<this.containment[1])i=this.containment[1]+this.offset.click.top;if(a.pageX-this.offset.click.left>this.containment[2])g=this.containment[2]+this.offset.click.left;if(a.pageY-this.offset.click.top>this.containment[3])i=
this.containment[3]+this.offset.click.top}if(c.grid){i=this.originalPageY+Math.round((i-this.originalPageY)/c.grid[1])*c.grid[1];i=this.containment?!(i-this.offset.click.top<this.containment[1]||i-this.offset.click.top>this.containment[3])?i:!(i-this.offset.click.top<this.containment[1])?i-c.grid[1]:i+c.grid[1]:i;g=this.originalPageX+Math.round((g-this.originalPageX)/c.grid[0])*c.grid[0];g=this.containment?!(g-this.offset.click.left<this.containment[0]||g-this.offset.click.left>this.containment[2])?
g:!(g-this.offset.click.left<this.containment[0])?g-c.grid[0]:g+c.grid[0]:g}}return{top:i-this.offset.click.top-this.offset.relative.top-this.offset.parent.top+(b.browser.safari&&this.cssPosition=="fixed"?0:this.cssPosition=="fixed"?-this.scrollParent.scrollTop():j?0:d.scrollTop()),left:g-this.offset.click.left-this.offset.relative.left-this.offset.parent.left+(b.browser.safari&&this.cssPosition=="fixed"?0:this.cssPosition=="fixed"?-this.scrollParent.scrollLeft():j?0:d.scrollLeft())}},_clear:function(){this.helper.removeClass("ui-draggable-dragging");
this.helper[0]!=this.element[0]&&!this.cancelHelperRemoval&&this.helper.remove();this.helper=null;this.cancelHelperRemoval=false},_trigger:function(a,c,d){d=d||this._uiHash();b.ui.plugin.call(this,a,[c,d]);if(a=="drag")this.positionAbs=this._convertPositionTo("absolute");return b.widget.prototype._trigger.call(this,a,c,d)},plugins:{},_uiHash:function(){return{helper:this.helper,position:this.position,absolutePosition:this.positionAbs,offset:this.positionAbs}}}));b.extend(b.ui.draggable,{version:"1.7.2",
eventPrefix:"drag",defaults:{addClasses:true,appendTo:"parent",axis:false,cancel:":input,option",connectToSortable:false,containment:false,cursor:"auto",cursorAt:false,delay:0,distance:1,grid:false,handle:false,helper:"original",iframeFix:false,opacity:false,refreshPositions:false,revert:false,revertDuration:500,scope:"default",scroll:true,scrollSensitivity:20,scrollSpeed:20,snap:false,snapMode:"both",snapTolerance:20,stack:false,zIndex:false}});b.ui.plugin.add("draggable","connectToSortable",{start:function(a,
c){var d=b(this).data("draggable"),j=d.options,g=b.extend({},c,{item:d.element});d.sortables=[];b(j.connectToSortable).each(function(){var i=b.data(this,"sortable");if(i&&!i.options.disabled){d.sortables.push({instance:i,shouldRevert:i.options.revert});i._refreshItems();i._trigger("activate",a,g)}})},stop:function(a,c){var d=b(this).data("draggable"),j=b.extend({},c,{item:d.element});b.each(d.sortables,function(){if(this.instance.isOver){this.instance.isOver=0;d.cancelHelperRemoval=true;this.instance.cancelHelperRemoval=
false;if(this.shouldRevert)this.instance.options.revert=true;this.instance._mouseStop(a);this.instance.options.helper=this.instance.options._helper;d.options.helper=="original"&&this.instance.currentItem.css({top:"auto",left:"auto"})}else{this.instance.cancelHelperRemoval=false;this.instance._trigger("deactivate",a,j)}})},drag:function(a,c){var d=b(this).data("draggable"),j=this;b.each(d.sortables,function(){this.instance.positionAbs=d.positionAbs;this.instance.helperProportions=d.helperProportions;
this.instance.offset.click=d.offset.click;if(this.instance._intersectsWith(this.instance.containerCache)){if(!this.instance.isOver){this.instance.isOver=1;this.instance.currentItem=b(j).clone().appendTo(this.instance.element).data("sortable-item",true);this.instance.options._helper=this.instance.options.helper;this.instance.options.helper=function(){return c.helper[0]};a.target=this.instance.currentItem[0];this.instance._mouseCapture(a,true);this.instance._mouseStart(a,true,true);this.instance.offset.click.top=
d.offset.click.top;this.instance.offset.click.left=d.offset.click.left;this.instance.offset.parent.left-=d.offset.parent.left-this.instance.offset.parent.left;this.instance.offset.parent.top-=d.offset.parent.top-this.instance.offset.parent.top;d._trigger("toSortable",a);d.dropped=this.instance.element;d.currentItem=d.element;this.instance.fromOutside=d}this.instance.currentItem&&this.instance._mouseDrag(a)}else if(this.instance.isOver){this.instance.isOver=0;this.instance.cancelHelperRemoval=true;
this.instance.options.revert=false;this.instance._trigger("out",a,this.instance._uiHash(this.instance));this.instance._mouseStop(a,true);this.instance.options.helper=this.instance.options._helper;this.instance.currentItem.remove();this.instance.placeholder&&this.instance.placeholder.remove();d._trigger("fromSortable",a);d.dropped=false}})}});b.ui.plugin.add("draggable","cursor",{start:function(){var a=b("body"),c=b(this).data("draggable").options;if(a.css("cursor"))c._cursor=a.css("cursor");a.css("cursor",
c.cursor)},stop:function(){var a=b(this).data("draggable").options;a._cursor&&b("body").css("cursor",a._cursor)}});b.ui.plugin.add("draggable","iframeFix",{start:function(){var a=b(this).data("draggable").options;b(a.iframeFix===true?"iframe":a.iframeFix).each(function(){b('<div class="ui-draggable-iframeFix" style="background: #fff;"></div>').css({width:this.offsetWidth+"px",height:this.offsetHeight+"px",position:"absolute",opacity:"0.001",zIndex:1000}).css(b(this).offset()).appendTo("body")})},
stop:function(){b("div.ui-draggable-iframeFix").each(function(){this.parentNode.removeChild(this)})}});b.ui.plugin.add("draggable","opacity",{start:function(a,c){a=b(c.helper);c=b(this).data("draggable").options;if(a.css("opacity"))c._opacity=a.css("opacity");a.css("opacity",c.opacity)},stop:function(a,c){a=b(this).data("draggable").options;a._opacity&&b(c.helper).css("opacity",a._opacity)}});b.ui.plugin.add("draggable","scroll",{start:function(){var a=b(this).data("draggable");if(a.scrollParent[0]!=
document&&a.scrollParent[0].tagName!="HTML")a.overflowOffset=a.scrollParent.offset()},drag:function(a){var c=b(this).data("draggable"),d=c.options,j=false;if(c.scrollParent[0]!=document&&c.scrollParent[0].tagName!="HTML"){if(!d.axis||d.axis!="x")if(c.overflowOffset.top+c.scrollParent[0].offsetHeight-a.pageY<d.scrollSensitivity)c.scrollParent[0].scrollTop=j=c.scrollParent[0].scrollTop+d.scrollSpeed;else if(a.pageY-c.overflowOffset.top<d.scrollSensitivity)c.scrollParent[0].scrollTop=j=c.scrollParent[0].scrollTop-
d.scrollSpeed;if(!d.axis||d.axis!="y")if(c.overflowOffset.left+c.scrollParent[0].offsetWidth-a.pageX<d.scrollSensitivity)c.scrollParent[0].scrollLeft=j=c.scrollParent[0].scrollLeft+d.scrollSpeed;else if(a.pageX-c.overflowOffset.left<d.scrollSensitivity)c.scrollParent[0].scrollLeft=j=c.scrollParent[0].scrollLeft-d.scrollSpeed}else{if(!d.axis||d.axis!="x")if(a.pageY-b(document).scrollTop()<d.scrollSensitivity)j=b(document).scrollTop(b(document).scrollTop()-d.scrollSpeed);else if(b(window).height()-
(a.pageY-b(document).scrollTop())<d.scrollSensitivity)j=b(document).scrollTop(b(document).scrollTop()+d.scrollSpeed);if(!d.axis||d.axis!="y")if(a.pageX-b(document).scrollLeft()<d.scrollSensitivity)j=b(document).scrollLeft(b(document).scrollLeft()-d.scrollSpeed);else if(b(window).width()-(a.pageX-b(document).scrollLeft())<d.scrollSensitivity)j=b(document).scrollLeft(b(document).scrollLeft()+d.scrollSpeed)}j!==false&&b.ui.ddmanager&&!d.dropBehaviour&&b.ui.ddmanager.prepareOffsets(c,a)}});b.ui.plugin.add("draggable",
"snap",{start:function(){var a=b(this).data("draggable"),c=a.options;a.snapElements=[];b(c.snap.constructor!=String?c.snap.items||":data(draggable)":c.snap).each(function(){var d=b(this),j=d.offset();this!=a.element[0]&&a.snapElements.push({item:this,width:d.outerWidth(),height:d.outerHeight(),top:j.top,left:j.left})})},drag:function(a,c){for(var d=b(this).data("draggable"),j=d.options,g=j.snapTolerance,i=c.offset.left,o=i+d.helperProportions.width,p=c.offset.top,e=p+d.helperProportions.height,f=
d.snapElements.length-1;f>=0;f--){var h=d.snapElements[f].left,k=h+d.snapElements[f].width,l=d.snapElements[f].top,m=l+d.snapElements[f].height;if(h-g<i&&i<k+g&&l-g<p&&p<m+g||h-g<i&&i<k+g&&l-g<e&&e<m+g||h-g<o&&o<k+g&&l-g<p&&p<m+g||h-g<o&&o<k+g&&l-g<e&&e<m+g){if(j.snapMode!="inner"){var n=Math.abs(l-e)<=g,q=Math.abs(m-p)<=g,r=Math.abs(h-o)<=g,s=Math.abs(k-i)<=g;if(n)c.position.top=d._convertPositionTo("relative",{top:l-d.helperProportions.height,left:0}).top-d.margins.top;if(q)c.position.top=d._convertPositionTo("relative",
{top:m,left:0}).top-d.margins.top;if(r)c.position.left=d._convertPositionTo("relative",{top:0,left:h-d.helperProportions.width}).left-d.margins.left;if(s)c.position.left=d._convertPositionTo("relative",{top:0,left:k}).left-d.margins.left}var t=n||q||r||s;if(j.snapMode!="outer"){n=Math.abs(l-p)<=g;q=Math.abs(m-e)<=g;r=Math.abs(h-i)<=g;s=Math.abs(k-o)<=g;if(n)c.position.top=d._convertPositionTo("relative",{top:l,left:0}).top-d.margins.top;if(q)c.position.top=d._convertPositionTo("relative",{top:m-d.helperProportions.height,
left:0}).top-d.margins.top;if(r)c.position.left=d._convertPositionTo("relative",{top:0,left:h}).left-d.margins.left;if(s)c.position.left=d._convertPositionTo("relative",{top:0,left:k-d.helperProportions.width}).left-d.margins.left}if(!d.snapElements[f].snapping&&(n||q||r||s||t))d.options.snap.snap&&d.options.snap.snap.call(d.element,a,b.extend(d._uiHash(),{snapItem:d.snapElements[f].item}));d.snapElements[f].snapping=n||q||r||s||t}else{d.snapElements[f].snapping&&d.options.snap.release&&d.options.snap.release.call(d.element,
a,b.extend(d._uiHash(),{snapItem:d.snapElements[f].item}));d.snapElements[f].snapping=false}}}});b.ui.plugin.add("draggable","stack",{start:function(){var a=b(this).data("draggable").options,c=b.makeArray(b(a.stack.group)).sort(function(d,j){return(parseInt(b(d).css("zIndex"),10)||a.stack.min)-(parseInt(b(j).css("zIndex"),10)||a.stack.min)});b(c).each(function(d){this.style.zIndex=a.stack.min+d});this[0].style.zIndex=a.stack.min+c.length}});b.ui.plugin.add("draggable","zIndex",{start:function(a,c){a=
b(c.helper);c=b(this).data("draggable").options;if(a.css("zIndex"))c._zIndex=a.css("zIndex");a.css("zIndex",c.zIndex)},stop:function(a,c){a=b(this).data("draggable").options;a._zIndex&&b(c.helper).css("zIndex",a._zIndex)}})})(jQuery);
(function(b){b.widget("ui.droppable",{_init:function(){var a=this.options,c=a.accept;this.isover=0;this.isout=1;this.options.accept=this.options.accept&&b.isFunction(this.options.accept)?this.options.accept:function(d){return d.is(c)};this.proportions={width:this.element[0].offsetWidth,height:this.element[0].offsetHeight};b.ui.ddmanager.droppables[this.options.scope]=b.ui.ddmanager.droppables[this.options.scope]||[];b.ui.ddmanager.droppables[this.options.scope].push(this);this.options.addClasses&&
this.element.addClass("ui-droppable")},destroy:function(){for(var a=b.ui.ddmanager.droppables[this.options.scope],c=0;c<a.length;c++)a[c]==this&&a.splice(c,1);this.element.removeClass("ui-droppable ui-droppable-disabled").removeData("droppable").unbind(".droppable")},_setData:function(a,c){if(a=="accept")this.options.accept=c&&b.isFunction(c)?c:function(d){return d.is(c)};else b.widget.prototype._setData.apply(this,arguments)},_activate:function(a){var c=b.ui.ddmanager.current;this.options.activeClass&&
this.element.addClass(this.options.activeClass);c&&this._trigger("activate",a,this.ui(c))},_deactivate:function(a){var c=b.ui.ddmanager.current;this.options.activeClass&&this.element.removeClass(this.options.activeClass);c&&this._trigger("deactivate",a,this.ui(c))},_over:function(a){var c=b.ui.ddmanager.current;if(!(!c||(c.currentItem||c.element)[0]==this.element[0]))if(this.options.accept.call(this.element[0],c.currentItem||c.element)){this.options.hoverClass&&this.element.addClass(this.options.hoverClass);
this._trigger("over",a,this.ui(c))}},_out:function(a){var c=b.ui.ddmanager.current;if(!(!c||(c.currentItem||c.element)[0]==this.element[0]))if(this.options.accept.call(this.element[0],c.currentItem||c.element)){this.options.hoverClass&&this.element.removeClass(this.options.hoverClass);this._trigger("out",a,this.ui(c))}},_drop:function(a,c){var d=c||b.ui.ddmanager.current;if(!d||(d.currentItem||d.element)[0]==this.element[0])return false;var j=false;this.element.find(":data(droppable)").not(".ui-draggable-dragging").each(function(){var g=
b.data(this,"droppable");if(g.options.greedy&&b.ui.intersect(d,b.extend(g,{offset:g.element.offset()}),g.options.tolerance)){j=true;return false}});if(j)return false;if(this.options.accept.call(this.element[0],d.currentItem||d.element)){this.options.activeClass&&this.element.removeClass(this.options.activeClass);this.options.hoverClass&&this.element.removeClass(this.options.hoverClass);this._trigger("drop",a,this.ui(d));return this.element}return false},ui:function(a){return{draggable:a.currentItem||
a.element,helper:a.helper,position:a.position,absolutePosition:a.positionAbs,offset:a.positionAbs}}});b.extend(b.ui.droppable,{version:"1.7.2",eventPrefix:"drop",defaults:{accept:"*",activeClass:false,addClasses:true,greedy:false,hoverClass:false,scope:"default",tolerance:"intersect"}});b.ui.intersect=function(a,c,d){if(!c.offset)return false;var j=(a.positionAbs||a.position.absolute).left,g=j+a.helperProportions.width,i=(a.positionAbs||a.position.absolute).top,o=i+a.helperProportions.height,p=c.offset.left,
e=p+c.proportions.width,f=c.offset.top,h=f+c.proportions.height;switch(d){case "fit":return p<j&&g<e&&f<i&&o<h;case "intersect":return p<j+a.helperProportions.width/2&&g-a.helperProportions.width/2<e&&f<i+a.helperProportions.height/2&&o-a.helperProportions.height/2<h;case "pointer":d=(a.positionAbs||a.position.absolute).left+(a.clickOffset||a.offset.click).left;a=(a.positionAbs||a.position.absolute).top+(a.clickOffset||a.offset.click).top;return c=b.ui.isOver(a,d,f,p,c.proportions.height,c.proportions.width);
case "touch":return(i>=f&&i<=h||o>=f&&o<=h||i<f&&o>h)&&(j>=p&&j<=e||g>=p&&g<=e||j<p&&g>e);default:return false}};b.ui.ddmanager={current:null,droppables:{"default":[]},prepareOffsets:function(a,c){var d=b.ui.ddmanager.droppables[a.options.scope],j=c?c.type:null,g=(a.currentItem||a.element).find(":data(droppable)").andSelf(),i=0;a:for(;i<d.length;i++)if(!(d[i].options.disabled||a&&!d[i].options.accept.call(d[i].element[0],a.currentItem||a.element))){for(var o=0;o<g.length;o++)if(g[o]==d[i].element[0]){d[i].proportions.height=
0;continue a}d[i].visible=d[i].element.css("display")!="none";if(d[i].visible){d[i].offset=d[i].element.offset();d[i].proportions={width:d[i].element[0].offsetWidth,height:d[i].element[0].offsetHeight};j=="mousedown"&&d[i]._activate.call(d[i],c)}}},drop:function(a,c){var d=false;b.each(b.ui.ddmanager.droppables[a.options.scope],function(){if(this.options){if(!this.options.disabled&&this.visible&&b.ui.intersect(a,this,this.options.tolerance))d=this._drop.call(this,c);if(!this.options.disabled&&this.visible&&
this.options.accept.call(this.element[0],a.currentItem||a.element)){this.isout=1;this.isover=0;this._deactivate.call(this,c)}}});return d},drag:function(a,c){a.options.refreshPositions&&b.ui.ddmanager.prepareOffsets(a,c);b.each(b.ui.ddmanager.droppables[a.options.scope],function(){if(!(this.options.disabled||this.greedyChild||!this.visible)){var d=b.ui.intersect(a,this,this.options.tolerance);if(d=!d&&this.isover==1?"isout":d&&this.isover==0?"isover":null){var j;if(this.options.greedy){var g=this.element.parents(":data(droppable):eq(0)");
if(g.length){j=b.data(g[0],"droppable");j.greedyChild=d=="isover"?1:0}}if(j&&d=="isover"){j.isover=0;j.isout=1;j._out.call(j,c)}this[d]=1;this[d=="isout"?"isover":"isout"]=0;this[d=="isover"?"_over":"_out"].call(this,c);if(j&&d=="isout"){j.isout=0;j.isover=1;j._over.call(j,c)}}}})}}})(jQuery);
