var a,userAgent=navigator.userAgent.toLowerCase(),is_opera=userAgent.indexOf("opera")!=-1,is_saf=userAgent.indexOf("applewebkit")!=-1||navigator.vendor=="Apple Computer, Inc.",is_webtv=userAgent.indexOf("webtv")!=-1,is_ie=userAgent.indexOf("msie")!=-1&&!is_opera&&!is_saf&&!is_webtv,is_ie4=is_ie&&userAgent.indexOf("msie 4.")!=-1,is_moz=navigator.product=="Gecko"&&!is_saf;isDOM=document.getElementById;isMSIE=document.all&&document.all.item;isNetscape4=document.layers;
isOpera5=(isOpera=window.opera)&&isDOM;isMSIE5=isDOM&&isMSIE&&!isOpera;isMozilla=isNetscape6=isDOM&&!isMSIE&&!isOpera;var std_loading_message="",best_voted_loaded=false,ug_serv="ultimate-guitar.com",old_comments_link="first",chk_view_coms_ready=0,show_menu=1;$(document).bind("click",function(){show_menu&&$(".selwin").hide();show_menu=1});$(".suggest").bind("mousedown",logger);function logger(){this.href="/xtra/sug.php?f="+this.href;$(this).unbind("mousedown",logger)}var votes_arr=[];
votes_arr[1]="poor";votes_arr[2]="not so good";votes_arr[3]="worth learning";votes_arr[4]="accurate";votes_arr[5]="excellent!";$(".selwin a").bind("click",function(b){$(".selcurr").html('<img src="http://img.'+ug_serv+'/img/sdbt.gif"> '+$(this).text());$("#w").val($(this).attr("value"));b.preventDefault()});function show_versions_area_pro(){$("#more_ver").slideDown(300);$("#vert .vers").css({width:"100px","padding-left":"50px"})}
function hide_versions_area_pro(){$("#more_ver").slideUp(300);$("#vert .vers").css({width:"","padding-left":""})}function show_versions_area(){$("#vert .vers").css({width:"100px","padding-left":"50px"});$("#gfk").hide();$(".divpos").slideDown(300)}function hide_versions_area(){$("#gfk").show();$("#vert .vers").css({width:"","padding-left":""});$(".divpos").slideUp(300)}function stars_fill(b){for(var c=1;c<6;c++)c<=b?$("#star"+c).addClass("cur"):$("#star"+c).removeClass()}
function VoteComment(b,c){$.ajax({type:"GET",url:"http://www.ultimate-guitar.com/vote0_comment.php?rowid="+b+"&content="+c+"&ajax=1&callback=?",data:"",dataType:"json",success:function(){var d=parseInt($("#"+b).html(),10),f="",h="";if(isNaN(d))d=0;f=d;f=c=="-1"?d-1:d+1;if(f>0){f="+"+f+"&nbsp;&nbsp;";h="green"}else if(f==0)f="";else{f=f+"&nbsp;&nbsp;";h="red"}d||$("#com_"+b+" .vup").after('<span id="'+b+'" class="f-right"></span>');$("#"+b).html(f).addClass(h);$("#com_"+b+" .vote_button").attr("href",
"javascript:void(0)");$("#com_"+b+" .vote_button").attr("onClick","func()");$("#com_"+b+" .vdn").addClass("votted");$("#com_"+b+" .vup").addClass("votedd")}})}
function viewComments(b,c,d){std_loading_message="<div class='loadmsg'><img src='http://img."+ug_serv+"/img/ajax-loader.gif'><p class='p2 verd fs-11' style='margin-bottom: 5px;'>Loading, please wait...</p><a href='http://www.ultimate-guitar.com/tab_comment.php?id="+b+"&artist_genre=0' class='fs-13 aria undl blue'>Click here if don't want to wait</a></div>";if(old_comments_link=="best_voted"||d=="best_voted"||old_comments_link=="first"){$("#comments").html(std_loading_message);c=c?"best_rated":"";
$.ajax({type:"GET",url:"http://www.ultimate-guitar.com/src/ajax/ajax.tab_comment.php?callback=?",dataType:"json",data:"tabid="+b+"&what="+c,success:function(f){$("#comments").html(f);sort_comments(d,b);f=document.cookie.split("; ");for(var h=0;h<f.length;h++){var k=f[h].split("=");if(k[0]=="bbuserid")var m=unescape(k[1])}m&&$(".comwr > .comh").each(function(){var e=$(this).attr("id").substr(4);$(this).find("a.vote_button:first").bind("click",function(){VoteComment(e,-1);$("div#com_"+e+" > a.vote_button").unbind("click");
return false});$(this).find("a.vote_button:eq(1)").bind("click",function(){VoteComment(e,10,1);$("div#com_"+e+" > a.vote_button").unbind("click");return false})});chk_view_coms_ready=1}})}else sort_comments(d,b);old_comments_link=d}
function sort_comments(b,c){if(b=="cor"){cnt_=$(".cor").parent().show();change_count_str(cnt_,b);$(".comm").parent().hide();$("#all_td").html("<a id='all' onClick='viewComments("+c+", false, \"all\")' href ='#comments' rel='nofollow' class='fs-10 verd blue undl'>All</a>");$("#cor_td").html("<b class='gray fs-10 bold' id='cor'>Corrections</b>");$("#com_td").html("<a id='com' onClick='viewComments("+c+", false, \"com\")' href ='#comments' rel='nofollow' class='fs-10 verd blue undl'>Comments</a>");$("#best_voted_td").html("<a href ='#comments'  id='best_voted'  onClick=\"viewComments("+
c+",true,'best_voted');\" rel='nofollow' class='fs-10 verd green undl'>Best Voted Corrections</a>")}else if(b=="com"){cnt_=$(".comm").parent().show();change_count_str(cnt_,b);$(".cor").parent().hide();$("#best_voted_td").html("<a href ='#comments'  id='best_voted'  onClick=\"viewComments("+c+",true,'best_voted');\" rel='nofollow' class='fs-10 verd green undl'>Best Voted Corrections</a>");$("#all_td").html("<a id='all' onClick='viewComments("+c+", false, \"all\")' href ='#comments' rel='nofollow' class='fs-10 verd blue undl'>All</a>");
$("#com_td").html("<b class='gray fs-10 bold' id='com'>Comments</b>");$("#cor_td").html("<a id='cor' onClick='viewComments("+c+", false, \"cor\")' href ='#comments' rel='nofollow' class='fs-10 verd blue undl'>Corrections</a>")}else if(b=="all"){cnt_=$(".comwr").show();change_count_str(cnt_,b);$("#best_voted_td").html("<a href ='#comments'  id='best_voted'  onClick=\"viewComments("+c+",true,'best_voted');\" rel='nofollow' class='fs-10 verd green undl'>Best Voted Corrections</a>");$("#all_td").html("<b class='gray fs-10 bold'>All</b>");
$("#com_td").html("<a id='com' onClick='viewComments("+c+", false, \"com\")' href ='#comments' rel='nofollow' class='fs-10 verd blue undl'>Comments</a>");$("#cor_td").html("<a id='cor' onClick='viewComments("+c+", false, \"cor\")' href ='#comments' rel='nofollow' class='fs-10 verd blue undl'>Corrections</a>")}else if(b=="best_voted"){cnt_=$(".comwr .cor").show();change_count_str(cnt_,b);$("#best_voted_td").html("<b class='gray fs-10 bold'>Best Voted Corrections</b>");$("#all_td").html("<a id='all' onClick='viewComments("+
c+", false, \"all\")' href ='#comments' rel='nofollow' class='fs-10 verd blue undl'>All</a>");$("#com_td").html("<a id='com' onClick='viewComments("+c+", false, \"com\")' href ='#comments' rel='nofollow' class='fs-10 verd blue undl'>Comments</a>");$("#cor_td").html("<a id='cor' onClick='viewComments("+c+", false, \"cor\")' href ='#comments' rel='nofollow' class='fs-10 verd blue undl'>Corrections</a>")}}
function change_count_str(b,c){var d="";if(b){b=b.length;if(c=="com"||c=="all")d=b==1?b+" comment posted":b+" comments posted";else if(c=="cor"||c=="best_voted")d=b==1?b+" correction posted":b+" corrections posted"}b||(d="Be the first to post your comment/correction");$("#count_rows").html('<b class="gray fs-10 bold">'+d+"</b>")}var q=0,accords=[];accords[1]="C";accords[2]="C#";accords[3]="D";accords[4]="D#";accords[5]="E";accords[6]="F";accords[7]="F#";accords[8]="G";accords[9]="G#";
accords[10]="A";accords[11]="A#";accords[12]="B";var cnt=accords.length-1;function str_pad(b,c,d,f){var h="";function k(m,e){for(var i="";i.length<e;)i+=m;return i=i.substr(0,e)}if(f!="STR_PAD_LEFT"&&f!="STR_PAD_RIGHT"&&f!="STR_PAD_BOTH")f="STR_PAD_RIGHT";if((h=c-b.length)>0)if(f=="STR_PAD_LEFT")b=k(d,h)+b;else if(f=="STR_PAD_RIGHT")b+=k(d,h);else if(f=="STR_PAD_BOTH"){h=k(d,Math.ceil(h/2));b=h+b+h;b=b.substr(0,c)}return b}
function build_applicature(b,c,d){c||$("#chords_list").empty();d=d.split(" ");for(acc in b){var f="",h=0,k="";if(c)f+='<div id="chord" onMouseOver="clearTimeout(a)"><div class="diag_head"><a href="#" id="alink" style="display: none;"></a><img src="http://img.'+ug_serv+'/img/move.gif" width="33" height="6"></div>';f+='<div class="diagwrap"><div class="chtit">';f+=acc+"</div>";var m=0;for(k1 in b[acc])k1!="suggested_fret"&&m++;for(k1 in b[acc])if(!(k1=="suggested_fret"||k1=="old_ch")){var e=q+"_"+h;
if(h)k="none";f+='<div style="display: '+k+'" id = "'+e+'"><div class="chfret">';var i=[];i=b[acc][k1].txt.split(" ");if(b[acc][k1].app)for(var j=5;j>=0;j--){var g="";if(i[j]!="x"&&b[acc][k1].app[j]!="capo"){var l=i[j]-b[acc][k1].fret;if(b[acc][k1].fret==0)switch(l){case 1:g="left:21px;";break;case 2:g="left:35px;";break;case 3:g="left:49px;";break;case 4:g="left:63px;";break;case 5:g="left:77px;";break}else switch(l){case 0:g="left:21px;";break;case 1:g="left:35px;";break;case 2:g="left:49px;";break;
case 3:g="left:63px;";break;case 4:g="left:77px;";break}l="";switch(j){case 0:l="top:55px;";break;case 1:l="top:44px;";break;case 2:l="top:33px;";break;case 3:l="top:22px;";break;case 4:l="top:11px;";break;case 5:l="top:0px;";break}if(b[acc][k1].fret!=0||i[j]!=0){var n="";switch(parseInt(b[acc][k1].app[j])){case 0:n="";break;case 1:n='<div class="f-1"></div>';break;case 2:n='<div class="f-2"></div>';break;case 3:n='<div class="f-3"></div>';break;case 4:n='<div class="f-4"></div>';break}f+='<div class="fingbg" style="'+
g+l+'">'+n+"</div>"}}l=0;var o;for(g=0;g<6;g++)i[g]!="x"&&l++;for(g=0;g<6;g++)if(b[acc][k1].app[g]=="capo"){o=1;break}else o=0;if(o)f+='<div class="barre" style="left:24px;"><img src="http://img.'+ug_serv+'/img/barre2.gif" width="3" height="2" style="margin-top:'+l+'0px"></div>'}f+='<div style="position:absolute; top:1px; left:5px">';for(g=5;g>=0;g--)f+='<div class="chname">'+d[g]+"</div>";f+='</div><div class="strings">';j=1;l=[];for(g=0;g<6;g++)if(!isNaN(i[g])&&j){l[g]='<div class="oo-str"></div>';
j=0}else l[g]=!j&&isNaN(i[g])&&i[g]!="x"?'<div class="o-str"></div>':i[g]=="x"?'<div class="x-str"></div>':'<div class="o-str"></div>';for(g=5;g>=0;g--)f+=l[g];i="&nbsp;";if(b[acc][k1].fret!=0)i=b[acc][k1].fret+" fr";j=h<1?q+"_"+(m-1):q+"_"+(h-1);g=h>=m-1?q+"_0":q+"_"+(h+1);f+='</div></div><div class="fs-10 fretnum">'+i+"</div>";f+='<div class="varctrl"><a href="javascript: void(0)" class="var-l" onClick="$(\'#'+e+"').hide();$('#"+j+'\').show();return false;"><img src="http://img.'+ug_serv+'/img/1x1.gif" width="1" height="1"></a><a href="javascript: void(0)" class="var-r" onClick="$(\'#'+
e+"').hide();$('#"+g+'\').show();return false;"><img src="http://img.'+ug_serv+'/img/1x1.gif" width="1" height="1"></a>Variation</div></div>';h++}if(c){f+="</div>";$("body").append(f)}else $("#chords_list").append(f);if(b[acc].suggested_fret){f=0;for(k2 in b[acc]){if(b[acc][k2].fret==b[acc].suggested_fret){$("#"+q+"_0").css("display","none");$("#"+q+"_"+f).css("display","");$("#"+q+"_0").prev().append(" ("+b[acc].suggested_fret+" fr.)");break}f++}}q++}}
function modulate_accord(b,c){c=parseInt(c,10);if(b.indexOf("/")!=-1){var d=b.split("/");if(d[1]!="9"){for(b=0;b<d.length;b++)d[b]=modulate_accord(d[b],c);return d.join("/")}}d=b.charAt(0).toUpperCase()+b.substring(1);if(d.charAt(0)=="H")d="B"+d.substring(1);if(d.charAt(0)=="B"&&d.indexOf("#")!=-1){d=d.replace("#","");d="C"+d.substring(1)}if(d.charAt(0)=="E"&&d.indexOf("#")!=-1){d=d.replace("#","");d="F"+d.substring(1)}var f="";if(d.indexOf("#")!=-1)f=d.charAt(0)+"#";else if(d.substring(1).indexOf("b")!=
-1){var h;for(b=1;b<=cnt;b++)if(accords[b]==d.charAt(0)){h=b;break}if(h==1)h=cnt;else h--;f=accords[h]}else f=d.charAt(0);for(b=1;b<=cnt;b++)if(accords[b]==f){h=b;break}h+=c;if(h<1)h+=cnt;if(h>cnt)h-=cnt;if(d.indexOf("#")!=-1)d=d.replace("#","");else if(d.substring(1).indexOf("b")!=-1)d=d.replace("b","");return d=accords[h]+d.substring(1)}
function ajax_change_ch_applicatures(b,c){b.tuning=c;$.ajax({type:"GET",url:"http://www.ultimate-guitar.com/src/ajax/ajax.get_applicatures.php?callback=?",data:b,dataType:"json",success:function(d){$("#cont span").each(function(){var f=$(this).html();for(ac in d)if(d[ac].old_ch==f){$(this).html(ac);break}});applicature=d;build_applicature(d,false,c);$("#transpose").attr("disabled","");$("#small_loader").hide()}})}var transpose_sum=0,sum_from_original=0,first_link="";
function transpose(b){$("#small_loader").show();$("#transpose").attr("disabled","disabled");var c=document.getElementById("gfk").value;transpose_sum+=parseInt(c,10);sum_from_original+=parseInt(c,10);if(transpose_sum>12)transpose_sum=12-transpose_sum;else if(transpose_sum<-12)transpose_sum+=12;if(sum_from_original>12)sum_from_original=12-sum_from_original;else if(sum_from_original<-12)sum_from_original+=12;$("#print_link").attr("href",first_link+"&transpose="+transpose_sum);var d=parseInt(c,10),f=
{},h={};$("#cont span").each(function(){var k=remove_frets_before_modulate($(this).text());f[k]=c==0?modulate_accord(k,-sum_from_original):modulate_accord(k,d)});ajax_change_ch_applicatures(f,b);if(c==0)sum_from_original=0;$("#original").length||$("#gfk").append('<option id=original value=0 style="color:#007FBF">Original version</option>')}function trim(b,c){c=!c?" s\u00a0":c.replace(/([\[\]\(\)\.\?\/\*\{\}\+\$\^\:])/g,"$1");c=new RegExp("^["+c+"]+|["+c+"]+$","g");return b.replace(c,"")}
function remove_frets_before_modulate(b){var c=/\([0-9XIV fr\.]+\)/;b=b.replace(c,"");return b=trim(b)}function chk_ch_diagrams_visible(){if(document.getElementById("disp_ch_diagrams").checked==true){$("#chords_list").html()||build_applicature(applicature,false,acc_tuning);$("#chords_list").fadeIn(500)}else $("#chords_list").hide();tab_scroller.getMoveAreaCoords();tab_scroller.setMoveAreaCoords()}
function chk_ch_highlight(){if(document.getElementById("disp_ch_highlight").checked==true){$("#cont span").css({color:"#007fbf",cursor:"pointer"});bind_hover()}else{$("#cont span").css({color:"#000",cursor:"auto"});$("#cont span").unbind("mouseover")}}function absPosition(b){for(var c=y=0;b;){c+=b.offsetLeft;y+=b.offsetTop;b=b.offsetParent}return{x:c,y:y}}
function bind_hover(){$("#cont span").mouseover(function(b){b=$(this).html();$("#chord")&&$("#chord").remove();var c=absPosition(this),d=c.y-165;c=c.x+25;for(var f in applicature)if(f==b){f={};f[b]=applicature[b];str=build_applicature(f,true,acc_tuning);$("#chord").css({position:"absolute",top:d,left:c,"z-index":++zind});$("#chord").mousedown(function(){$(this).css("z-index",++zind)});$("#chord").draggable({handle:".diag_head",stop:function(){bind_hover();$("#drag_stats").length&&$.ajax({type:"post",
url:"/src/ajax/ajax.count_chart_drags.php"})},start:function(){$("#cont span").unbind("mouseover");if($(this)){uniq_cnt++;$(this).attr("id","ch_"+uniq_cnt);$("#ch_"+uniq_cnt+" .diag_head").find("a").attr("id","alink_"+uniq_cnt);$("#alink_"+uniq_cnt).bind("click",function(){var h=$(this).attr("id").substr(6);$("#ch_"+h).remove();return false});$("#alink_"+uniq_cnt).show()}$("#chord").remove()}});clearTimeout(a);break}$("#chord").mouseleave(setInetv)})}
function hide_scroll(){if(document.getElementById("scroll").style.display=="none"){$("#scroll").show();$("#arr_scroll").css({background:"url(http://img."+ug_serv+"/img/arr.gif) 0px -40px"})}else{$("#scroll").hide();$("#arr_scroll").css({background:"url(http://img."+ug_serv+"/img/arr.gif)"})}tab_scroller.getMoveAreaCoords();tab_scroller.setMoveAreaCoords()}
function setInetv(){if(document.getElementById("alink"))if(document.getElementById("alink").style.display=="none")a=setTimeout(function(){clearTimeout(a);$("#chord").remove()},400)}
function get_mouse_position(b){var c=0,d=0;if(!b)b=window.event;if(b.pageX||b.pageY){c=b.pageX;d=b.pageY}else if(b.clientX||b.clientY){c=b.clientX+(document.documentElement.scrollLeft||document.body.scrollLeft)-document.documentElement.clientLeft;d=b.clientY+(document.documentElement.scrollTop||document.body.scrollTop)-document.documentElement.clientTop}return{x:c,y:d}}
function TabScroller(){this.of_top=$("#whole_scroll").offset().top;this.scrolling_speed=0;this.sticked=true;this.height_gradient=0;this.to="";this.save_scroll_position=false;this.memorized_position=20;this.getMoveAreaCoords();this.setMoveAreaCoords();$("#drop, #drop2").droppable({over:function(){$("#drop").css({background:"url(http://img."+ug_serv+"/img/border_drag.gif) no-repeat top right"})},drop:function(){$("#whole_scroll").animate({top:0,left:0},100);$("#drop").css({"background-image":""});tab_scroller.stick();
tab_scroller.save_scroll_position=false;tab_scroller.memorized_position=20},out:function(){$("#drop").css({"background-image":""})}});$("#transparent_area_for_scroll").droppable({over:function(){$(".scropac").css({opacity:".6",filter:"alpha(opacity=60)"})},out:function(){$(".scropac").css({opacity:".9",filter:"alpha(opacity=90)"})},accept:"#whole_scroll"});$("#speed").click(function(b){b=get_mouse_position(b);var c=$("#speed");c=c.offset();height=b.y-c.top;if(height%14)height=Math.ceil(height/14)*
14;tab_scroller.setHeight(height,true);tab_scroller.changeSpeed(height/14*100)});$("#speed").mousemove(function(b){b=get_mouse_position(b);var c=$("#speed");c=c.offset();height_=b.y-c.top;tab_scroller.setHeight(height_,false)});$("#speed").mouseleave(function(){tab_scroller.setHeight(tab_scroller.height_gradient,true)});$("#dec_speed").click(function(){tab_scroller.decSpeed()});$("#inc_speed").click(function(){tab_scroller.incSpeed()});$().keydown(function(b){switch(b.keyCode){case 27:tab_scroller.setHeight(0,
true);tab_scroller.changeSpeed(0);break;case 43:case 107:tab_scroller.scrolling_speed!=500&&tab_scroller.incSpeed();break;case 45:case 109:tab_scroller.decSpeed();break}});$(window).scroll(function(){scroll_top=$(window).scrollTop();var b=$("#scroll").css("display")=="none"?$("#scroll_height").height()+12:235;if(scroll_top>=tab_scroller.of_top)tab_scroller.save_scroll_position=true;else{tab_scroller.save_scroll_position=false;tab_scroller.memorized_position=$("#whole_scroll").offset().top-tab_scroller.of_top}if(tab_scroller.memorized_position<=
20)tab_scroller.memorized_position=20;if(!tab_scroller.sticked||tab_scroller.sticked&&tab_scroller.scrolling_speed>0)if($(window).scrollTop()+20>=$("#whole_scroll").offset().top&&!tab_scroller.save_scroll_position)$("#whole_scroll").css({top:$(window).scrollTop()+20-tab_scroller.of_top});else tab_scroller.save_scroll_position&&$("#whole_scroll").css({top:scroll_top+tab_scroller.memorized_position-tab_scroller.of_top+"px"});if($("#whole_scroll").offset().top+b>=scroll_top+$(window).height()-20){if(!tab_scroller.sticked){$("#whole_scroll").css({top:scroll_top+
$(window).height()-20-b-tab_scroller.of_top+"px"});tab_scroller.memorized_position=$("#whole_scroll").offset().top-tab_scroller.of_top}}else $(window).scrollTop()+20>=$("#whole_scroll").offset().top&&tab_scroller.scrolling_speed>0&&$("#whole_scroll").css({top:$(window).scrollTop()+20-tab_scroller.of_top})})}a=TabScroller.prototype;a.getMoveAreaCoords=function(){this.move_area_coords=$("#area_for_scroll").offset()};
a.setMoveAreaCoords=function(){var b=$("#scroll").css("display")=="none"?$("#scroll_height").height()+12:235,c=$(window).height(),d,f;$("#whole_scroll").draggable("destroy");$("#whole_scroll").draggable({handle:"#move_scroll",containment:[0,this.of_top,$("#area_for_scroll").width()-77,this.move_area_coords.top+$("#area_for_scroll").height()-b],start:function(){tab_scroller.unstick()},stop:function(){tab_scroller.save_scroll_position=$(window).scrollTop()>tab_scroller.of_top?true:false;tab_scroller.memorized_position=
$("#whole_scroll").offset().top-$(window).scrollTop()},drag:function(h,k){if(!is_ie){f=k.offset.top;d=window.scroll_top;if(d>tab_scroller.of_top){d+20>=f&&$(window).scrollTop(f-20);tab_scroller.memorized_position=f-d}else tab_scroller.memorized_position=f-tab_scroller.of_top;f+b>=d+c-20&&$(window).scrollTop(f+b-c+20)}}})};
a.doScroll=function(){$.browser.opera||$("body:not(:animated)").animate({scrollTop:"+=1"},1,"linear");$("html").animate({scrollTop:"+=1"},1,"linear");timeout_interval=275-this.scrolling_speed/2;this.to=setTimeout("tab_scroller.doScroll()",timeout_interval)};
a.changeSpeed=function(b){if(b<=0)b=0;if(b>500)b=500;this.scrolling_speed=b;if(this.sticked&&this.scrolling_speed>0&&$(window).scrollTop()>this.of_top){this.unstick();$("#whole_scroll").animate({top:$(window).scrollTop()-this.of_top+20+"px"},1000);setTimeout(function(){clearTimeout(tab_scroller.to);tab_scroller.memorized_position=20;tab_scroller.doScroll()},1000)}else if(this.scrolling_speed){clearTimeout(this.to);this.doScroll()}else clearTimeout(this.to)};
a.incSpeed=function(){this.scrolling_speed+=100;this.changeSpeed(this.scrolling_speed);this.height_gradient+=14;this.setHeight(this.height_gradient,true)};a.decSpeed=function(){this.scrolling_speed-=100;this.changeSpeed(this.scrolling_speed);this.height_gradient-=14;this.setHeight(this.height_gradient,true)};
a.setHeight=function(b,c){if(c)if(b>70)b=this.height_gradient=70;else if(b<0)b=this.height_gradient=0;else this.height_gradient=b;else if(b>70)b=70;else if(b<0)b=0;$("#speed").html('<div id="speed_d" style="background:url(http://img.'+ug_serv+"/img/speed.png) -22px 0px; height:"+b+'px; line-height: 0px;">&nbsp;</div>')};a.stick=function(){this.sticked=true};a.unstick=function(){this.sticked=false};
function show_all_acc(){$("#all_acc").css("display")=="none"?$("#all_acc").show():$("#all_acc").hide()}function add_ch(b){b=build_applicature_txt(b);$("#list").prepend(b)}
function build_applicature_txt(b){var c=tuning_.split(" "),d="",f="";d+='<div style="width: 190px; float: left; margin: 1px;background:#f9f9f9; border:solid #ddd 1px; " id="all_ch_'+q+'"><div style="float: left; width: 92%;text-align:center; font-size:14px; line-height:22px; color:#000; padding:5px 0px"><b>';d+=b+'</b></div><div class="x" style="float: right; padding: 3px; cursor: pointer;" onClick="$(\'#all_ch_'+q+"').remove();\">x</div>";var h=0;for(k1 in applicature[b])k1!="suggested_fret"&&k1!=
"old_ch"&&h++;var k=0;for(k1 in applicature[b])if(!(k1=="suggested_fret"||k1=="old_ch")){var m=q+"_"+k;f=k?"none":"";d+='<div style="clear: both; display: '+f+'" id = "'+m+'"><div style="padding:1px 5px 0px 5px;  width:175px;">';f=[];f=applicature[b][k1].txt.split(" ");for(var e=0,i,j=0;j<6;j++)f[j]!="x"&&e++;for(j=0;j<6;j++)if(applicature[b][k1].app[j]=="capo"){i=1;break}else i=0;var g=[];e="";for(e=5;e>=0;e--)if(f[e]=="x")g[e]=str_pad(c[e],2," ","STR_PAD_RIGHT")+"|---|---|---|---|---| x<br>";else if(f[e]==
"0")g[e]=str_pad(c[e],2," ","STR_PAD_RIGHT")+"|---|---|---|---|---| o<br>";else{j=f[e]-applicature[b][k1].fret;if(applicature[b][k1].fret==0)switch(j){case 1:g[e]=str_pad(c[e],2," ","STR_PAD_RIGHT")+"|-";g[e]+=i?"<b>1</b>":"<b>"+applicature[b][k1].app[e]+"</b>";g[e]+="-|---|---|---|---| o<br>";break;case 2:g[e]=str_pad(c[e],2," ","STR_PAD_RIGHT")+"|-";g[e]+=i?"<b>1</b>":"-";g[e]+="-|-<b>"+applicature[b][k1].app[e]+"</b>-|---|---|---| o<br>";break;case 3:g[e]=str_pad(c[e],2," ","STR_PAD_RIGHT")+"|-";
g[e]+=i?"<b>1</b>":"-";g[e]+="-|---|-<b>"+applicature[b][k1].app[e]+"</b>-|---|---| o<br>";break;case 4:g[e]=str_pad(c[e],2," ","STR_PAD_RIGHT")+"|-";g[e]+=i?"<b>1</b>":"-";g[e]+="-|---|---|-<b>"+applicature[b][k1].app[e]+"</b>-|---| o<br>";break;case 5:g[e]=str_pad(c[e],2," ","STR_PAD_RIGHT")+"|-";g[e]+=i?"<b>1</b>":"-";g[e]+="-|---|---|---|-<b>"+applicature[b][k1].app[e]+"</b>-| o<br>";break}else switch(j){case 0:g[e]=str_pad(c[e],2," ","STR_PAD_RIGHT")+"|-";g[e]+=i?"<b>1</b>":"<b>"+applicature[b][k1].app[e]+
"</b>";g[e]+="-|---|---|---|---| o<br>";break;case 1:g[e]=str_pad(c[e],2," ","STR_PAD_RIGHT")+"|-";g[e]+=i?"<b>1</b>":"-";g[e]+="-|-<b>"+applicature[b][k1].app[e]+"</b>-|---|---|---| o<br>";break;case 2:g[e]=str_pad(c[e],2," ","STR_PAD_RIGHT")+"|-";g[e]+=i?"<b>1</b>":"-";g[e]+="-|---|-<b>"+applicature[b][k1].app[e]+"</b>-|---|---| o<br>";break;case 3:g[e]=str_pad(c[e],2," ","STR_PAD_RIGHT")+"|-";g[e]+=i?"<b>1</b>":"-";g[e]+="-|---|---|-<b>"+applicature[b][k1].app[e]+"</b>-|---| o<br>";break;case 4:g[e]=
str_pad(c[e],2," ","STR_PAD_RIGHT")+"|-";g[e]+=i?"<b>1</b>":"-";g[e]+="-|---|---|---|-<b>"+applicature[b][k1].app[e]+"</b>-| o<br>";break}}e="<pre>"+g[5]+g[4]+g[3]+g[2]+g[1]+g[0]+"</pre></div>";d+=e;f="&nbsp;";if(applicature[b][k1].fret!=0)f=applicature[b][k1].fret+" fr.";e=k<1?q+"_"+(h-1):q+"_"+(k-1);j=k>=h-1?q+"_0":q+"_"+(k+1);d+='<div class="fs-10" style="padding:0px 0px 0px 23px; color:#000;">'+f+"</div>";d+='<div class="fs-10" style="padding: 10px 0px; text-align: center; " id="vers"><a href="javascript: void(0)" class="var-l"><img src="http://img.'+
ug_serv+'/img/1x1.gif" onClick="$(\'#'+m+"').hide();$('#"+e+'\').show();return false;"></a>&nbsp;&nbsp;Variation&nbsp;&nbsp;<a href="javascript: void(0)" class="var-r"><img src="http://img.'+ug_serv+'/img/1x1.gif" onClick="$(\'#'+m+"').hide();$('#"+j+"').show();return false;\"></a></div></div>";k++}q++;return d}
function get_check(b){$(".com_area").removeClass("com_area");$("#pleaseselect").hide();$("#com_msg").fadeOut(500);if(b=="comm"){$("#cb_comment").attr("checked","checked");$("#cb_correction").attr("checked","")}else if(b=="corr"){$("#cb_correction").attr("checked","checked");$("#cb_comment").attr("checked","")}}
function check_com_area(){$("#com_msg").fadeOut(500);if(!$("#cb_correction").attr("checked")&&!$("#cb_comment").attr("checked")&&$("#content_").val().length<10){$("#com_msg").fadeIn(500).html("<img src='http://img."+ug_serv+"/img/warning_icon.gif' align=absmiddle width=16 height=16> Please select type above <br><img src='http://img."+ug_serv+"/img/warning_icon.gif' align=absmiddle width=16 height=16> Your comment is too short");return false}else if($("#content_").val().length<10){$("#com_msg").fadeIn(500).html("<img src='http://img."+
ug_serv+"/img/warning_icon.gif' align=absmiddle width=16 height=16> Your comment is too short");return false}else if(!$("#cb_correction").attr("checked")&&!$("#cb_comment").attr("checked")){$("#com_msg").fadeIn(500).html("<img src='http://img."+ug_serv+"/img/warning_icon.gif' align=absmiddle width=16 height=16> Please select type above");return false}return true}function add_lines(){var b=parseInt($("#content_").css("height"));b+=50;$("#content_").css("height",b+"px")}
function refferers(b,c){if(b!=-1){if(loc.indexOf("corr")!=-1)viewComments(c,false,"cor");else loc.indexOf("comm")!=-1?viewComments(c,false,"com"):viewComments(c,false,"all");_interval=setInterval(function(){if(chk_view_coms_ready){var d=loc.indexOf("#");d=loc.substr(d);d=$(d).offset().top;$(window).scrollTop(d);clearInterval(_interval)}},100)}};
