document.write('<div id="jambocast_wrapper"></div>');
document.write('	\<script src="http://player.jambovideonetwork.com/js/jc.js?20090819"\>\</script\>');
document.write('	\<script src="http://media.jambocast.com/jcp/extern.js"\>\</script\>');
document.write('	\<script src="http://media.jambocast.com/jcp/swfobject.js"\>\</script\>');
document.write('	\<script type="text/javascript" src="http://cdna.tremormedia.com/acudeo/banners.js"\>\</script\>');
document.write('	<!--[if IE]>');
document.write('	\<script type="text/javascript"\>');
document.write('	function fixOutOfMemoryError() {');
document.write('	  __flash_unloadHandler = function() {};');
document.write('	  __flash_savedUnloadHandler = function() {};');
document.write('	}');
document.write('	window.attachEvent("onbeforeunload", fixOutOfMemoryError);');
document.write('	\</script\>');
document.write('	<![endif]-->');
document.write('	<style type="text/css" media="screen">    object { outline:none; }</style>');
document.write('	\<script src="http://player.jambovideonetwork.com/js/jc_out.php?pubsite_id=12496&pr=12694&layout=bottom&preview=0&video_id=0"\>\</script\>');
document.write('	');